name: page-deploy
on: 
  push:
    branches:
      - master
    # paths:
    #   - src/*
jobs:
  build:
    runs-on : ubuntu-latest
    name: build&deploy
    steps:
      - name : copy files
        uses : actions/checkout@v2

      - name : env
        uses : actions/setup-node@v1

      - name : Install Dependencies
        run : npm install
      
      - name : build
        run : npm run build:prod
      
      # 利用action把build好的文件上传到服务器/var/www/react-app路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: appleboy/scp-action@master
        env: 
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: root
          PORT: 22
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:  
          source: 'dist/*'  # 对应我们项目build的文件夹路径
          target: '/usr/local/nginx/html/templates/home/1' #对应线上应该存放的地址
          strip_components: 1
          rm: true
        
  

