name: page-deploy
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on : ubuntu-latest
    name: build&deploy
    steps:
      # 复制当前文件夹文件
      - name : copy files
        uses : actions/checkout@v2

      # 安装对应环境
      - name : env
        uses : actions/setup-node@v1

      #安装依赖
      - name : Install Dependencies
        run : npm install
      
      # 打包
      - name : build
        run : npm run build:prod
      
      # 部署到服务器
      - name: deploy file to server
        uses: appleboy/scp-action@master
        # 服务器ssh信息
        env: 
          HOST: ${{ secrets.SERVER_IP }}
          USERNAME: root
          PORT: 22
          # 生成私钥，公钥，将私钥保存到仓库secrets,将公钥保存到服务器 /root/.ssh/authorized_keys文件中
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:  
          # 对应我们项目build的文件夹路径
          source: 'dist/*'  
          # 对应线上应该存放的地址
          target: '/usr/local/nginx/html/templates/home/1' 
          # 删除dist文件夹名称
          strip_components: 1
          # 删除target地址下的所有文件
          rm: true
  message: 
    needs: build
    name: post message to ding
    steps:
      - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL: ${{ secrets.webhook }}
        data: "github actions finished"
        
  

